version: "3.8"
services:
  torproxy:
    build: .
    container_name: torproxy
    environment:
      - TZ=Europe/Moscow
    volumes:
#      - /srv/dev-disk-by-uuid-e8eb8931-061e-4b20-977f-196617efe9d7/docker/torproxy/etc/tor:/etc/tor
#      - /srv/dev-disk-by-uuid-e8eb8931-061e-4b20-977f-196617efe9d7/docker/torproxy/var/lib/tor:/var/lib/tor
    ports:
      - 8118:8118
      - 9050:9050
    restart: unless-stopped